spring:
  application:
    name: virtual-registry
  main:
    allow-bean-definition-overriding: true

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    
  server:
    waitTimeInMsWhenSyncEmpty: 0
  
logging:
  level:
    com.netflix:
            eureka: ON
            discovery: OFF