spring:
  application:
    name: eureka-server
  main:
    allow-bean-definition-overriding: true
  batch:
    job:
      enabled: false
    initialize-schema: always
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always 

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    
  server:
    waitTimeInMsWhenSyncEmpty: 0
  
logging:
  level:
    com.netflix:
            eureka: ON
            discovery: OFF
